export const FETCH_BLOG = 'FETCH_BLOG';
export const FETCH_SINGLE_BLOG = 'FETCH_SINGLE_BLOG';
export const SET_BLOG_PAGE = 'SET_BLOG_PAGE';
export const SET_BLOG_FILTER = 'SET_BLOG_FILTER';
export const SET_BLOG_FILTER_ITEMS_PER_PAGE = 'SET_BLOG_FILTER_ITEMS_PER_PAGE';


export const FETCH_BLOG_FILTERED_ITEMS = 'FETCH_BLOG_FILTERED_ITEMS';

export const FETCH_BLOG_FILTERED_ITEMS_REQUESTED = 'FETCH_BLOG_FILTERED_ITEMS_REQUESTED';
export const FETCH_BLOG_FILTERED_ITEMS_SUCCEEDED = 'FETCH_BLOG_FILTERED_ITEMS_SUCCEEDED';
export const FETCH_BLOG_FILTERED_ITEMS_FAILED = 'FETCH_BLOG_FILTERED_ITEMS_FAILED';


export const FETCH_BLOG_PAGE = 'FETCH_BLOG_PAGE';