export const FETCH_BLOG = 'FETCH_BLOG';
export const FETCH_SINGLE_BLOG = 'FETCH_SINGLE_BLOG';
export const SET_BLOG_PAGE = 'SET_BLOG_PAGE';
export const SET_BLOG_FILTER = 'SET_BLOG_FILTER';
export const SET_BLOG_FILTER_ITEMS_PER_PAGE = 'SET_BLOG_FILTER_ITEMS_PER_PAGE';

export const FETCH_FILTERED_ITEMS_REQUESTED = 'blog/FETCH_FILTERED_ITEMS_REQUESTED';
export const FETCH_FILTERED_ITEMS_SUCCEEDED = 'blog/FETCH_FILTERED_ITEMS_SUCCEEDED';
export const FETCH_FILTERED_ITEMS_FAILED = 'blog/FETCH_FILTERED_ITEMS_FAILED';

export const FETCH_BLOG_PAGE = 'FETCH_BLOG_PAGE';
